recipes:
    global:
        - applications::create_var_chef_cache
    mac_os_x:
        - nodejs::default
      #  - homebrewalt::default
        - osxdefaults::set_computer_name
attributes:
    osxdefaults:
        computername: link
    git:
        name: Adam Fortuna
        email: Adam Fortuna
#    homebrewalt:
#        apps:
#            - git
#            - git-extras
#        cask_apps:
#            - google-chrome
#            - sourcetree
#            - slack
#	    - things
#            - dropbox
#            - evernote
#            - bartender
#            - caffeine
#            - vlc
#            - vagrant
#            - virtualbox
#        cask_fonts:
#            - inconsolata
  
